### ISSUE TITLE
How to send push notifications from firebase to specific devices?

### ISSUE THREAD

**Issue by sabres207** [khmyznikov/ios-pwa-wrap#10]
in AppDelegate.swift, do I need to uncomment anything? What are the comments about swizzling?
Also, what if I want to use OneSignal in my project. is it possible? is there any documentation for that?

thank you!

**Comment by khmyznikov** [comment]
https://github.com/khmyznikov/ios-pwa-wrap/issues/2
For One signal use their docs for Swift. It's possible.
