### ISSUE TITLE
Unable to run base application 

### ISSUE THREAD

**Issue by Wordlesschunk** [khmyznikov/ios-pwa-wrap#13]
Im struggling to get the repo to work just from cloned
Steps i take:
clone repo
pod install (within root dir of project)
open .xcworkspace
press play within xcode 
<img width="657" alt="image" src="https://github.com/khmyznikov/ios-pwa-wrap/assets/22942020/65fd7d24-c0e2-43e4-a48b-fb406d167342">

**Comment by khmyznikov** [comment]
Glad you figured out. I did a few updates recently, don't forget to pull the repo. Let me know how the things worked for you.
