### ISSUE TITLE
Notifications not working in production

### ISSUE THREAD

**Issue by sans1994** [khmyznikov/ios-pwa-wrap#14]
@khmyznikov Hello. I have finally successfully implemented notifications using ios-pwa-wrap. However, I still have a small problem with notifications in production.

When the application server is running locally (localhost) and I launch the app through Xcode referring to let rootUrl = URL(string: "http://localhost:8080")!, notifications are delivered successfully. But when the settings specify let rootUrl = URL(string: "https://mysite.com")! for the test server domain, notifications do not come through.

Could it be an issue with the bundleId settings in the Firebase project? I have a test server (https://state.mysite.com) and a production server (https://mysite.com). In Firebase, the bundleId is specified for the production server, but for testing in TestFlight, I build with the test server domain.

Can you suggest where I might have gone wrong?

**Comment by khmyznikov** [comment]
Hi, figured out?

**Comment by sans1994** [comment]
> Hi, figured out?

Hi! Yes, everything is great – I successfully implemented the notification logic. The problem was due to my inattention – incorrect credentials for Firebase and the GoogleService-Info.plist file.
