### ISSUE TITLE
open youtube and twitch app

### ISSUE THREAD

**Issue by ivankravchyk2023** [khmyznikov/ios-pwa-wrap#4]
hello, i am new to ios, could you help me fix the problem of refreshing app when you try to open url of youtube and twitch.tv app from pwa ios. If i add youtube and twitch domain it's openning in webviev without navigation like in app, if add to autorigins it's show toolbar "done" even on page of my pwa where iframe embed. How i can i open these url in app if installed or just in safari?
thank you so much!

**Comment by khmyznikov** [comment]
Can you show how it looks if you trying to open these links without adding to autorigins or any other origins?
